# CI Build. Runs on every commit to any branch but not PRs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runs-on: ubuntu-latest

  - job: BuildAndTest
    variables:
      PYTHON_ENV: 'python'
    steps:
    - checkout: self
      submodules: true
      persistCredentials: true
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
    - script: npm install
      displayName: 'Install dependencies'
    - script: npm run build
      displayName: Build project
    - script: npm test
      displayName: NPM test
