# Updates Crowdin with any changes in the English translation file (/assets/locales/en/translation.json)

name: Update Crowdin English Resources

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Crowdin Update
      run: node ./ci-jobs/crowdin-update-resources.js
      env:
        CROWDIN_PROJECT_ID: appium-desktop
        CROWDIN_PROJECT_KEY: ${{ secrets.CROWDIN_PROJECT_KEY }}
      
